services:
  backend:
    build:
      context: ../gin-backend
      dockerfile: Dockerfile.dev
    container_name: gin_backend_dev
    working_dir: /app
    command: ["air", "-c", "/app/.air.toml"]
    volumes:
      - ../gin-backend:/app
      - go_cache:/go/pkg/mod
    env_file:
      - ../.env
    environment:
      API_PORT: ${BACKEND_PORT:-8080}
      DB_HOST: postgres_db
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      app_internal_net:
        aliases:
          - gin_backend    # Alias para que Nginx lo resuelva

volumes:
  go_cache:
